syntax = "proto3";

import "google/protobuf/timestamp.proto";

package product.variant.read.v1;

option csharp_namespace = "ProductVariantReadService.Api.Grpc.V1.Protos";

service ProductVariantReadService {
	rpc GetVariantsByProductId(GetVariantsByProductIdRequest) returns (GetVariantsByProductIdResponse);
	rpc GetOwnVariantsByProductId(GetOwnVariantsByProductIdRequest) returns (GetOwnVariantsByProductIdResponse);
}

message VariantPublicDto {
	string variant_id = 1;
	string product_id = 2;
	string vendor_id = 3;
	PriceInfoDto price = 4;
	StockInfoDto stock = 5;
	ReviewSummaryDto review_summary = 6;
	repeated ProductVariantAttributeDto attributes = 7;
	repeated VariantImageDto images = 8;
}

message VariantOwnerDto {
	string variant_id = 1;
	string product_id = 2;
	string vendor_id = 3;
	string sku = 4;
    DimensionsInfoDto dimensions = 5;
    WeightInfoDto weight = 6;
    string barcode = 7;
	PriceInfoDto price = 8;
	StockInfoDto stock = 9;
	ReviewSummaryDto review_summary = 10;
	repeated ProductVariantAttributeDto attributes = 11;
	repeated VariantImageDto images = 12;
	google.protobuf.Timestamp created_at = 13;
    google.protobuf.Timestamp updated_at = 14;
}

message PriceInfoDto {
	int64 amount_minor = 1;
	optional int64 old_amount_minor = 2;
}

message StockInfoDto {
	bool in_stock = 1;
}

message DimensionsInfoDto {
	double length = 1;
	double width = 2;
	double height = 3;
	string unit = 4;
}

message WeightInfoDto {
	double weight = 1;
	string unit = 2;
}

message ReviewSummaryDto {
	double average_rating = 1;
	int32 total_count = 2;
}

message ProductVariantAttributeDto {
	string characteristic_id = 1;
	string name = 2;
	string value = 3;
	string char_type = 4;
	optional string group_name = 5;
}

message VariantImageDto {
	string url = 1;
	string alt = 2;
	int32 sort_order = 3;
	bool is_main = 4;
}

message GetVariantsByProductIdRequest {
	string product_id = 1;
	string currency_code = 2;
}

message GetVariantsByProductIdResponse {
	repeated VariantPublicDto variants = 1;
}

message GetOwnVariantsByProductIdRequest {
	string product_id = 1;
	string vendor_id = 2;
	string currency_code = 3;
}

message GetOwnVariantsByProductIdResponse {
	repeated VariantOwnerDto variants = 1;
}